#!/usr/bin/python

import subprocess
import urllib
import os
import sys
import md5

#Python translation for Perl script that gets Gravatars for Gource (code.google.com/gource)

def getEmail(committer):
	return committer[committer.index("<"):].strip("<>")
def getAuthor(committer):
	return committer[:committer.index("<")].strip()

size = 90
outputDir = ".bzr/avatar"

if not os.path.exists(".bzr"):
	print "This is not a Bazaar branch. Exiting now."
	sys.exit()
if not os.path.exists(outputDir):
	os.mkdir(outputDir)

output = subprocess.Popen( "bzr stats" , stdout=subprocess.PIPE , shell=True ).stdout.read()
#print output
output = output.splitlines()
#print output
for i in range(len(output)):
	output[i] = output[i].strip()
	output[i] = output[i].lstrip('0123456789 ')
#print output
while "Other names:" in output:
	output.remove("Other names:")
#print output

for author in output:
	if not "<" in author: continue
	print "Getting image for " + author + "."
	m = md5.new()
	m.update(getEmail(author).lower())
	#print "Getting image for", getAuthor(author)
	grav_url = "http://www.gravatar.com/avatar/" + m.hexdigest()
	urllib.urlretrieve(grav_url , outputDir + "/" + getAuthor(author) + ".png")

os.system("gource --user-image-dir " + outputDir)
